_target_: src.dataloader.BaseDataset

genome: ${paths.genome.fa}
blacklist_file: ${paths.genome.blacklist}
unmap_file: ${paths.genome.unmappable}

chroms: null
signal_files: ${cell_line.bw}

unmap_threshold: null
logspace: True
memmap: False

window_size: 1024
margin_size: 512
bin_size: ${model.bin_size}
generated: ${paths.dir.generated} 