defaults:
  - base
  - _self_

_target_: src.dataloader.BoundedDataset
unmap_threshold: 0.35
lower_bound: ${cell_line.lower_bound}
step_size: 1024
random_shift: True
augmentations: True
bin_size: ${model.bin_size}
is_train: True
