defaults:
  - paths: biomed
  - model: dcnn
  - dataset/train_bounded@datasets.train_bounded
  - dataset/train_wg@datasets.train_wg
  - dataset/val_wg@datasets.val_wg
  - dataset/eval_wg@datasets.eval_wg
  - dataset/eval_peaks@datasets.eval_peaks
  - dataset/robustness_wg@datasets.robustness_wg
  - dataset/robustness_peaks@datasets.robustness_peaks
  - _self_

run_script: null
cell_line: null
experiment_name: null

train_dataset: ${datasets.train_wg}
val_dataset: ${datasets.val_wg}
eval_datasets:
  peaks: ${datasets.eval_peaks}
  wg: ${datasets.eval_wg}
robustness_datasets:
  peaks: ${datasets.robustness_peaks}
  wg: ${datasets.robustness_wg}

bench_settings:
  binning_type: max
  adjust_offset: False

# ----- TASK SPECIFIC CONFIGS -----

# train a fold in range [0, 4] on CV
train:
  fold: null
  save_file: ${experiment_name}_${model.name}_${cell_line.exp_name}_fold${train.fold}
  trainer:
    max_epochs: 70
  train_dataset: ${train_dataset}
  val_dataset: ${val_dataset}
  
# train on all chroms
train_all:
  save_file: ${experiment_name}_${model.name}_${cell_line.exp_name}_all
  trainer:
    max_epochs: 40
  train_dataset: ${train_dataset}
  val_dataset: ${val_dataset}

# using all folds predict for reference and variant on all mutations
# requires cell line properties: snv, atac_bam
predict_snv:
  output_path: ${paths.dir.generated}/predictions/${experiment_name}_${model.name}_${cell_line.exp_name}.csv

# export predictions as bigwigs
export_predictions:
  chrom: null

eval:
  fold: null
  save_file: ${experiment_name}_${model.name}_${cell_line.exp_name}_fold${train.fold}