dir:
  data_path: null
  checkpoint: ${paths.dir.data_path}/checkpoint
  logs: ${paths.dir.data_path}/logs
  generated: ${paths.dir.data_path}/generated
  tmp: ${paths.dir.data_path}/generated/tmp

predictions:
  scores: ${paths.dir.data_path}/results.csv
  robustness: ${paths.dir.data_path}/robustness.csv

genome:
  fa: null
  blacklist: null
  unmappable: null
